version: 0.2

phases:
  install:
    commands:
      - echo "Let's install! =D"
      - "npm install"
    finally:
      - echo "Hopefully it installed"
  build:
    commands:
      - echo "Build time =D"
      - ls
      - cd ..
      - ls
      - "npm run build"
artifacts:
  files:
    - "./build/*"
    - "./node_modules"
    - "./package.json"
  discard-paths: no
  s3-prefix: ExperimentsFrontend

